sudo: required
language: node_js

node_js:
- "8.12.0"
  
services:
- postgresql

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_script:
# Client
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- cd client && npm install
- npm install -g @angular/cli
- ng build

script: 
# Client
- cd ../client && ng test

notifications:
email: false
