language: node_js

node_js:
- "8.12.0"
  
services:
- postgresql

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta


before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- npm install -g @angular-cli
- npm install -g karma
- npm install
- ng build

script: 
# Client
ng test
karma start client/src/karma.conf.js --single-run

  
notifications:
email: false
