language: java
jdk: oraclejdk8

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE scheduler;" -U postgres
  - psql -c "CREATE USER scheduler WITH PASSWORD 'scheduler';" -U postgres

script:
  - cd server && mvn verify

notifications:
  email: false
