language: node_js

node_js:
- "8.12.0"
  
services:
- postgresql

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_script:
# Client
- cd client && npm install
- npm install -g @angular-cli
#- npm install -g karma
- ng build
- ng serve

# Server
- cd ../server && npm install
- psql -c 'create database travis_ci_test;' -U postgres
- node app.js

script: 
# Client
 - cd ../client && ng test
#karma start client/src/karma.conf.js --single-run
# Server
#some tests here
  
notifications:
email: false
