sudo: required
language: node_js

node_js:
- "8.12.0"
  
services:
- postgresql

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_script:
# Client
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- cd client && npm install
- npm install -g angular-cli
#- npm install -g karma
- ng build

# Server
#- cd ../server && npm install
#- psql -c 'create database travis_ci_test;' -U postgres
#- node app.js

script: 
# Client
#- ng serve
- cd ../client && ng test
#karma start client/src/karma.conf.js --single-run
# Server
#some tests here
  
notifications:
email: false
