---
version: "2.1"

services:

  web-client:
    depends_on:
      - web-server
    build: ./client
    image: appointment-scheduler-client
    container_name: appointment-scheduler-client
    ports:
      - "80:80"

  web-server:
    depends_on:
      - db
    build: ./server
    image: appointment-scheduler-server
    container_name: appointment-scheduler-server
    environment:
      # can also be 'db'
      # overrides the DB_HOST variable in .env
      DB_HOST: postgres
    ports:
      - "3000:3000"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:5000"

  db:
    image: postgres:11
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: scheduler
      POSTGRES_USER: scheduler
      POSTGRES_PASSWORD: scheduler
    volumes:
      - "pgdata:/var/lib/postgresql/data"

volumes:
  pgdata:
    name: pgdata