---
version: "3.4"
services:
  web-client:
    depends_on:
      - web-server
    build: ./client
    image: appointment-scheduler-client
    container_name: appointment-scheduler-client
    ports:
      - "80:80"

  web-server:
    depends_on:
      - db
    build: server-old
    image: appointment-scheduler-server
    container_name: appointment-scheduler-server
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: scheduler
      DB_PASSWORD: scheduler
      DB_NAME: scheduler

  db:
    image: postgres:11
    container_name: postgres
    environment:
      POSTGRES_DB: scheduler
      POSTGRES_USER: scheduler
      POSTGRES_PASSWORD: scheduler
    volumes:
      - "pgdata:/var/lib/postgresql/data"

volumes:
  pgdata:
    name: pgdata
