---
version: "3.4"
services:
  web-client:
    build: ./client
    image: appointment-scheduler-client
    container_name: appointment-scheduler-client
    network_mode: host

  web-server:
    build: ./server
    image: appointment-scheduler-server
    container_name: appointment-scheduler-server
    network_mode: host

  db:
    image: postgres
    container_name: postgres
    network_mode: host
    environment:
      POSTGRES_DB: scheduler
      POSTGRES_USER: scheduler
      POSTGRES_PASSWORD: scheduler
    volumes:
      - "pgdata:/var/lib/postgresql/data"

volumes:
  pgdata:
    name: pgdata
